# Dev-image med nodemon og devDependencies
FROM node:20-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/ ./
COPY frontend/ ./public/

EXPOSE 3000
CMD ["npm", "run", "dev"]
